### ISSUE TITLE
Cant import Node Template

### ISSUE THREAD

**Issue by qroac** [Lelik13a/Zabbix-OpenVZ#2]
Using latest versions from naizvoru.com/raspbian/zabbix Repository:

Kategorie "Memory" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory commitment" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory commitment in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory limit" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory limit in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory utilization" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Allocated memory utilization in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Low memory commitment" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Low memory commitment in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Low memory utilization" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Low memory utilization in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Memory + swap commitment" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Memory + swap commitment in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Memory + swap utilization" auf "Template OpenVZ Node" erstellt.
Datenpunkt "Memory + swap utilization in %" auf "Template OpenVZ Node" erstellt.
Datenpunkt "RAM utilization" auf "Template OpenVZ Node" erstellt.
Datenpunkt "RAM utilization in %" auf "Template OpenVZ Node" erstellt.
mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Discover  OpenVZ container','0','','','3600','0','','','0','0','','0','','','','','0','','','','','',Array,'30','Discover  OpenVZ container/\r\nScript /etc/zabbix/vzdiscover.sh','openvz.ct.discovery','','10108','1','4','0',NULL,'23762')] [Unknown column 'Array' in 'field list']
Fehler beim Ausführen der SQL-Anweisung "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Discover  OpenVZ container','0','','','3600','0','','','0','0','','0','','','','','0','','','','','',Array,'30','Discover  OpenVZ container/\r\nScript /etc/zabbix/vzdiscover.sh','openvz.ct.discovery','','10108','1','4','0',NULL,'23762')".

**Comment by Lelik13a** [comment]
Seems like zabbix database version mismatch. What you zabbix version?. I am use 2.4.5. And this template must work on 2.2 too.

**Comment by qroac** [comment]
These are my versions:

```
$ dpkg -l  |grep zabbix
ii  zabbix-agent                          1:2.2.5-1+0.1                           armhf        network monitoring solution - agent
ii  zabbix-frontend-php                   1:2.2.5-1+0.1                           all          network monitoring solution - PHP front-end
ii  zabbix-server-mysql                   1:2.2.5-1+0.1                           armhf        network monitoring solution - server (using MySQL)
```

The errors before show, that the script tries to work with a string but has an array to work with.
Looking in the VALUES list of the statement I see Array in the values list. It is the position of the "filters" field.

**Comment by Lelik13a** [comment]
Seems like zabbix bug: https://support.zabbix.com/browse/ZBX-8192
I upload template without discovery rule, try import and create discovery manually:
Name: Discover  OpenVZ container
Key: openvz.ct.discovery

Host prototypes:
Host name: {#CTID}
Visible name: {#CTHOST}

Groups: OpenVZ CT
Group prototypes: {#VENAME}

Linked templates: Template OpenVZ CT

![discovery 1](https://cloud.githubusercontent.com/assets/12905969/9158390/6566d926-3f40-11e5-9681-24e5bc81b7dc.png)
![discovery 2](https://cloud.githubusercontent.com/assets/12905969/9158391/658c877a-3f40-11e5-9486-1b70229a7418.png)
![discovery 3](https://cloud.githubusercontent.com/assets/12905969/9158393/65c97d06-3f40-11e5-828d-eb4e55053166.png)
![discovery 4](https://cloud.githubusercontent.com/assets/12905969/9158392/65b1a190-3f40-11e5-8e03-a824fb90469b.png)

**Comment by jangaraj** [comment]
Note: Try to export template from Zabbix 2.2. It should be imported to Zabbix 2.4 without problem. I have had the same problem and now it's not a issue anymore.

**Comment by faustoroger** [comment]
On Zabbix 3.0, in the field Description, only change vzdiscover.sh to vzdiscover.pl.
