### ISSUE TITLE
Too many processes

### ISSUE THREAD

**Issue by peterlaws** [Lelik13a/Zabbix-OpenVZ#3]
Can I ask why, or how comes, the limit is set at 90 processes? Where do I change this limit?

Sorry if this is easy.

**Comment by Lelik13a** [comment]
Hello.
Limit set in template "Template OpenVZ CT" macros "{$PROC_CT_WARN}".
You can set it as you like.

**Comment by peterlaws** [comment]
I'm a dumbass. Thank you.
