### ISSUE TITLE
Trigger "Too many processes" flapping every minutes

### ISSUE THREAD

**Issue by itJunky** [Lelik13a/Zabbix-OpenVZ#4]
How can i change trigger condition value at autodiscovery host items?
In this template i have a macros {$PROC_CT_WARN} but i can't set my macros and value to autodiscovered host.

**Comment by Lelik13a** [comment]
You can set a macros {$PROC_CT_WARN} to parent host (hardware node), it will be inherited to auto-discovered CT host. This is zabbix restriction.

I added trigger "the number of processes is above average per hour", maybe it will be more useful.

**Comment by itJunky** [comment]
It's not flexible!
On any virtual machines i set any limits. And i need one trigger value for one VM and some other value for other VM on same hardware node.

**Comment by Lelik13a** [comment]
I agree, but zabbix auto-discovery works so :(.
You can add every CT host manually and apply template "Template OpenVZ CT" on them. This allows you to adjust the settings on each container. Host name must be "{#VENAME}.{#CTID}" where CTID - key value.

**Comment by Lelik13a** [comment]
Zabbix 3.0 release :).
With many changes in macros.
https://www.zabbix.com/documentation/3.0/manual/introduction/whatsnew300

**Comment by itJunky** [comment]
Cool, but i don't see changaes with this functionality =(

**Comment by Lelik13a** [comment]
Changed trigger "too many processes" to prevent flapps (in new template).
